use strum_macros::EnumString;

use crate::{block::block_properties::BlockProperties, item::item::Item};

#[allow(non_camel_case_types)]
#[derive(Clone, Copy, PartialEq, Eq, EnumString)]
pub enum Block {
    NONE, ERROR, AIR, STONE, DIRT, GRASS_BLOCK_1, GRASS_BLOCK_2, GRASS_1, FLOWER_1, OAK_LOG, OAK_LEAVES,
    CLOVERS, LAMP, OAK_LEAVES_BLOCK, GRASS_BLOCK_3, HOE, FARM, OAK_LOG_NORTH, OAK_LOG_EAST, MAPLE_LEAVES_BLOCK,
    MAPLE_LEAVES, OAK_PLANKS, LILY_OF_THE_VALLEY_1, LILY_OF_THE_VALLEY_2, LILY_OF_THE_VALLEY_3,
    CHERRY_LEAVES_FLOWERING, PEBBLES, CACTUS, STRIPPED_OAK_LOG
}
impl Block {
    pub fn is_air(self) -> bool {
        self == Block::AIR
    }
    pub fn properties(self) -> &'static BlockProperties {
        &BLOCK_PROPERTIES[self as usize]
    }
}

pub const BLOCK_PROPERTIES: &[BlockProperties] = &[
    BlockProperties {
        is_plant_growable: false,
        hardness: 0,
        is_transparent: false,
        render_neighbors: false,
        is_folliage: false,
        can_collide: true,
        breakable: false,
        placable: false,
        wind_affected: false,
        ambient_occlusion: false,
        textures: [0; 6],
        block_model: "default",
        item: Item::NONE,
        offset: 0.0
    },
    BlockProperties {
        is_plant_growable: false,
        hardness: 0,
        is_transparent: false,
        render_neighbors: false,
        is_folliage: false,
        can_collide: true,
        breakable: true,
        placable: true,
        wind_affected: false,
        ambient_occlusion: true,
        textures: [51; 6],
        block_model: "default",
        item: Item::NONE,
        offset: 0.0
    },
    BlockProperties {
        is_plant_growable: false,
        hardness: 0,
        is_transparent: true,
        render_neighbors: true,
        is_folliage: false,
        can_collide: false,
        breakable: false,
        placable: false,
        wind_affected: false,
        ambient_occlusion: false,
        textures: [0; 6],
        block_model: "default",
        item: Item::NONE,
        offset: 0.0
    },
    BlockProperties {
        is_plant_growable: false,
        hardness: 5,
        is_transparent: false,
        render_neighbors: false,
        is_folliage: false,
        can_collide: true,
        breakable: true,
        placable: true,
        wind_affected: false,
        ambient_occlusion: true,
        textures: [0; 6],
        block_model: "default",
        item: Item::STONE,
        offset: 0.0
    },
    BlockProperties {
        is_plant_growable: true,
        hardness: 1,
        is_transparent: false,
        render_neighbors: false,
        is_folliage: false,
        can_collide: true,
        breakable: true,
        placable: true,
        wind_affected: false,
        ambient_occlusion: true,
        textures: [43; 6],
        block_model: "default",
        item: Item::DIRT,
        offset: 0.0
    },
    BlockProperties {
        is_plant_growable: true,
        hardness: 1,
        is_transparent: false,
        render_neighbors: false,
        is_folliage: false,
        can_collide: true,
        breakable: true,
        placable: true,
        wind_affected: false,
        ambient_occlusion: true,
        textures: [48, 48, 40, 43, 48, 48],
        block_model: "default",
        item: Item::GRASS_BLOCK,
        offset: 0.0
    },
    BlockProperties {
        is_plant_growable: true,
        hardness: 1,
        is_transparent: false,
        render_neighbors: false,
        is_folliage: false,
        can_collide: true,
        breakable: true,
        placable: true,
        wind_affected: false,
        ambient_occlusion: true,
        textures: [48, 48, 56, 43, 48, 48],
        block_model: "default",
        item: Item::GRASS_BLOCK,
        offset: 0.0
    },
    BlockProperties {
        is_plant_growable: true,
        hardness: 1,
        is_transparent: true,
        render_neighbors: true,
        is_folliage: true,
        can_collide: false,
        breakable: true,
        placable: false,
        wind_affected: true,
        ambient_occlusion: false,
        textures: [24; 6],
        block_model: "grass",
        item: Item::GRASS,
        offset: 0.25
    },
    BlockProperties {
        is_plant_growable: false,
        hardness: 1,
        is_transparent: true,
        render_neighbors: true,
        is_folliage: true,
        can_collide: false,
        breakable: true,
        placable: false,
        wind_affected: true,
        ambient_occlusion: false,
        textures: [32; 6],
        block_model: "grass",
        item: Item::FLOWER,
        offset: 0.25
    },
    BlockProperties {
        is_plant_growable: false,
        hardness: 5,
        is_transparent: false,
        render_neighbors: false,
        is_folliage: false,
        can_collide: true,
        breakable: true,
        placable: true,
        wind_affected: false,
        ambient_occlusion: true,
        textures: [31, 31, 47, 47, 31, 31],
        block_model: "default",
        item: Item::OAK_LOG,
        offset: 0.0
    },
    BlockProperties {
        is_plant_growable: false,
        hardness: 1,
        is_transparent: true,
        render_neighbors: true,
        is_folliage: true,
        can_collide: true,
        breakable: true,
        placable: true,
        wind_affected: true,
        ambient_occlusion: true,
        textures: [5; 6],
        block_model: "leaves",
        item: Item::OAK_LEAVES,
        offset: 0.25
    },
    BlockProperties {
        is_plant_growable: false,
        hardness: 1,
        is_transparent: true,
        render_neighbors: true,
        is_folliage: true,
        can_collide: false,
        breakable: true,
        placable: false,
        wind_affected: true,
        ambient_occlusion: false,
        textures: [52; 6],
        block_model: "clover",
        item: Item::FLOWER,
        offset: 0.25
    },
    BlockProperties {
        is_plant_growable: false,
        hardness: 1,
        is_transparent: false,
        render_neighbors: false,
        is_folliage: false,
        can_collide: true,
        breakable: true,
        placable: true,
        wind_affected: false,
        ambient_occlusion: false,
        textures: [57; 6],
        block_model: "default",
        item: Item::LAMP,
        offset: 0.0
    },
    BlockProperties {
        is_plant_growable: false,
        hardness: 1,
        is_transparent: true,
        render_neighbors: true,
        is_folliage: true,
        can_collide: true,
        breakable: true,
        placable: true,
        wind_affected: true,
        ambient_occlusion: true,
        textures: [53; 6],
        block_model: "default",
        item: Item::OAK_LEAVES_BLOCK,
        offset: 0.0
    },
    BlockProperties {
        is_plant_growable: true,
        hardness: 1,
        is_transparent: false,
        render_neighbors: false,
        is_folliage: false,
        can_collide: true,
        breakable: true,
        placable: true,
        wind_affected: false,
        ambient_occlusion: true,
        textures: [48, 48, 58, 43, 48, 48],
        block_model: "default",
        item: Item::GRASS_BLOCK,
        offset: 0.0
    },
    BlockProperties {
        is_plant_growable: false,
        hardness: 1,
        is_transparent: false,
        render_neighbors: true,
        is_folliage: false,
        can_collide: true,
        breakable: true,
        placable: false,
        wind_affected: false,
        ambient_occlusion: false,
        textures: [0; 6],
        block_model: "hoe",
        item: Item::HOE,
        offset: 0.0
    },
    BlockProperties {
        is_plant_growable: true,
        hardness: 1,
        is_transparent: false,
        render_neighbors: true,
        is_folliage: false,
        can_collide: true,
        breakable: true,
        placable: true,
        wind_affected: false,
        ambient_occlusion: true,
        textures: [43, 43, 54, 43, 43, 43],
        block_model: "farm",
        item: Item::GRASS_BLOCK,
        offset: 0.0
    },
    BlockProperties {
        is_plant_growable: false,
        hardness: 5,
        is_transparent: false,
        render_neighbors: false,
        is_folliage: false,
        can_collide: true,
        breakable: true,
        placable: true,
        wind_affected: false,
        ambient_occlusion: true,
        textures: [31, 31, 31, 31, 47, 47],
        block_model: "default",
        item: Item::OAK_LOG,
        offset: 0.0
    },
    BlockProperties {
        is_plant_growable: false,
        hardness: 5,
        is_transparent: false,
        render_neighbors: false,
        is_folliage: false,
        can_collide: true,
        breakable: true,
        placable: true,
        wind_affected: false,
        ambient_occlusion: true,
        textures: [47, 47, 31, 31, 31, 31],
        block_model: "default",
        item: Item::OAK_LOG,
        offset: 0.0
    },
    BlockProperties {
        is_plant_growable: false,
        hardness: 1,
        is_transparent: true,
        render_neighbors: true,
        is_folliage: true,
        can_collide: true,
        breakable: true,
        placable: true,
        wind_affected: true,
        ambient_occlusion: true,
        textures: [55; 6],
        block_model: "default",
        item: Item::MAPLE_LEAVES_BLOCK,
        offset: 0.0
    },
    BlockProperties {
        is_plant_growable: false,
        hardness: 1,
        is_transparent: true,
        render_neighbors: true,
        is_folliage: true,
        can_collide: true,
        breakable: true,
        placable: true,
        wind_affected: true,
        ambient_occlusion: true,
        textures: [63; 6],
        block_model: "leaves",
        item: Item::MAPLE_LEAVES,
        offset: 0.25
    },
    BlockProperties {
        is_plant_growable: false,
        hardness: 5,
        is_transparent: false,
        render_neighbors: false,
        is_folliage: false,
        can_collide: true,
        breakable: true,
        placable: true,
        wind_affected: false,
        ambient_occlusion: true,
        textures: [23; 6],
        block_model: "default",
        item: Item::OAK_PLANKS,
        offset: 0.0
    },
    BlockProperties {
        is_plant_growable: false,
        hardness: 1,
        is_transparent: true,
        render_neighbors: true,
        is_folliage: true,
        can_collide: false,
        breakable: true,
        placable: false,
        wind_affected: true,
        ambient_occlusion: false,
        textures: [8; 6],
        block_model: "flower",
        item: Item::FLOWER,
        offset: 0.25
    },
    BlockProperties {
        is_plant_growable: false,
        hardness: 1,
        is_transparent: true,
        render_neighbors: true,
        is_folliage: true,
        can_collide: false,
        breakable: true,
        placable: false,
        wind_affected: true,
        ambient_occlusion: false,
        textures: [9; 6],
        block_model: "flower",
        item: Item::FLOWER,
        offset: 0.25
    },
    BlockProperties {
        is_plant_growable: false,
        hardness: 1,
        is_transparent: true,
        render_neighbors: true,
        is_folliage: true,
        can_collide: false,
        breakable: true,
        placable: false,
        wind_affected: true,
        ambient_occlusion: false,
        textures: [8; 6],
        block_model: "grass",
        item: Item::FLOWER,
        offset: 0.25
    },
    BlockProperties {
        is_plant_growable: false,
        hardness: 1,
        is_transparent: true,
        render_neighbors: true,
        is_folliage: true,
        can_collide: true,
        breakable: true,
        placable: true,
        wind_affected: true,
        ambient_occlusion: true,
        textures: [61; 6],
        block_model: "leaves",
        item: Item::OAK_LEAVES,
        offset: 0.25
    },
    BlockProperties {
        is_plant_growable: false,
        hardness: 0,
        is_transparent: false,
        render_neighbors: true,
        is_folliage: false,
        can_collide: false,
        breakable: true,
        placable: true,
        wind_affected: false,
        ambient_occlusion: false,
        textures: [0; 6],
        block_model: "pebbles",
        item: Item::PEBBLE,
        offset: 0.25
    },
    BlockProperties {
        is_plant_growable: false,
        hardness: 3,
        is_transparent: false,
        render_neighbors: true,
        is_folliage: true,
        can_collide: true,
        breakable: true,
        placable: true,
        wind_affected: false,
        ambient_occlusion: true,
        textures: [36, 36, 37, 37, 36, 36],
        block_model: "pillar",
        item: Item::CACTUS,
        offset: 0.0
    },
    BlockProperties {
        is_plant_growable: false,
        hardness: 5,
        is_transparent: false,
        render_neighbors: false,
        is_folliage: false,
        can_collide: true,
        breakable: true,
        placable: true,
        wind_affected: false,
        ambient_occlusion: true,
        textures: [39, 39, 62, 64, 39, 39],
        block_model: "default",
        item: Item::OAK_LOG,
        offset: 0.0
    },
];
